name: CI/CD

env:
  CI: true

on:
  push:
    branches: [master]
    paths-ignore:
      - "docs/**"
      - "*.md"
jobs:
  ci-cd:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: gregoranders/nodejs-project-info@v0.0.11
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - name: NPM CI
        run: npm install

      - name: Repository build
        run: npm run build

      - name: Tests (with coverage)
        run: npm test -- --coverage

      - name: Build website (Github pages)
        run: npm run build-doc --if-present

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v1.1.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare distribution
        if: "contains(steps.projectinfo.outputs.version, '-')"
        run: cp -r ./@types ./dist/@types && cp package.json index.d.ts README.md LICENSE CHANGELOG.md CONTRIBUTING.md CODE_OF_CONDUCT.md ./dist
